# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Path Tracer
email: "cem.gundogdu@metu.edu.tr"
description: >- # this means to ignore newlines until "baseurl:"
  My blog page for the Path Tracer I will write for Advanced Ray Tracing
  course at Middle East Technical University.
baseurl: "/pathtracer"
# twitter_username:
github_username:  gcem
minimal_mistakes_skin: default
search: true

# Build settings
# theme: minima
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Istanbul

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Cem Gündoğdu"
  avatar : "/assets/images/me.jpg"
  bio    : "Third year (more precisely, 3.0417th year) computer engineering student at METU."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://cemgundogdu.com/"
    - label: "E-mail"
      icon: "fa fa-envelope "
      url: "mailto:cem.gundogdu@metu.edu.tr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gcem"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/cem-gundogdu"

footer:
  links:
  - label: "E-mail"
    icon: "fa fa-envelope "
    url: "mailto:cem.gundogdu@metu.edu.tr"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/gcem"
  - label: "LinkedIn"
    icon: "fab fa-fw fa-instagram"
    url: "https://linkedin.com/in/cem-gundogdu"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true # table of contents
      excerpt_separator: <!--more-->
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
